import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>MS | Team 20</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <Link href="/login">
            <p>
              Get started by&nbsp;
              <code className={styles.code}>Login Here</code>
            </p>
          </Link>
          <Link href="/register">
            <p>
              Or Get started by&nbsp;
              <code className={styles.code}>Registering</code>
            </p>
          </Link>
          <div>
            <a
              href="#"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              <Image
                src="https://tinymiracles.com/wp-content/uploads/2022/03/Logo.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>
      </main>
    </>
  )
}
